apache/airavata

- thrift-interface-descriptions/generate-thrift-stubs.sh
If a `thrift` executable is already in the $PATH, prefer to use that instead
of the hardcoded path /usr/local/bin/thrift
> Fix generate-thrift-stubs.sh to auto-find thrift executable

- modules/cloud/ansible-playbooks/README.md
- modules/cloud/ansible-playbooks/roles/openstack/tasks/main.yml
- modules/cloud/ansible-playbooks/roles/openstack/vars/main.yml
- modules/cloud/ansible-playbooks/roles/openstack/vars/openstack-credentials.yml
- modules/cloud/ansible-playbooks/site.yml
PR contains the following change to the cloud module: 
- Ansible script to provision instances in OpenStack based cloud.
Here are some details of all changes made:
- Added ansible script to provision multiple instances in OpenStack based cloud. These provisioned instances can then be used to deploy a mesos-marathon cluster on top of them using mesos deployment script. This is in addition to Shameera's existing script for EC2 provisioning.
- Updated the README file to include steps for running the playbook. This includes details about configuring the OpenStack credentials and updating the instance names.
> Implement Ansible playbook for OpenStack resource provisioning

- modules/credential-store/credential-store-service/src/main/java/org/apache/airavata/credential/store/credential/Credential.java
To keep Credential.java compatible with the previous version, I'm adding
the serialVersionUID from the previous version. This will allow
serialized instances of the old version to be deserialized with the new
version.
> Add serialVersionUID for previous version of class

- airavata-api/airavata-api-server/src/main/java/org/apache/airavata/api/server/handler/AiravataServerHandler.java
- airavata-api/airavata-client-sdks/airavata-php-sdk/src/main/resources/lib/Airavata/API/Airavata.php
- modules/configuration/server/src/main/resources/airavata-default-xacml-policy.xml
- thrift-interface-descriptions/airavata-apis/airavata_api.thrift
Adds the following API server methods
* getExperimentByAdmin
* cloneExperimentByAdmin
These methods allow an admin to see and clone experiments for which they don't have the READ sharing permission.
> AIRAVATA-2207 Admin users can't see experiment summaries

- airavata-api/airavata-api-server/src/main/java/org/apache/airavata/api/server/handler/AiravataServerHandler.java
- modules/registry/registry-core/src/main/java/org/apache/airavata/registry/core/experiment/catalog/impl/NotificationRegistry.java
Instead of returning the difference as a long and casting to an int,
which risks integer overflow, just return 1 or -1 corresponding to the
sign of the difference.
Note: this branch was branched from master which is ahead of develop by a few spurious commits.  My change for this bug fix is really just NotificationRegistry.java change.
> AIRAVATA-2282 notification sort: Prevent int overflow

- airavata-api/airavata-data-models/src/main/java/org/apache/airavata/model/workspace/Gateway.java
- airavata-services/profile-service/profile-service-commons/src/main/java/org/apache/airavata/service/profile/commons/utils/QueryConstants.java
- airavata-services/profile-service/profile-service-server/src/main/java/org/apache/airavata/service/profile/handlers/TenantProfileServiceHandler.java
- airavata-services/profile-service/profile-service-stubs/src/main/java/org/apache/airavata/service/profile/tenant/cpi/TenantProfileService.java
- airavata-services/profile-service/profile-tenant-core/src/main/java/org/apache/airavata/service/profile/tenant/core/repositories/TenantProfileRepository.java
- thrift-interface-descriptions/data-models/experiment-catalog-models/workspace_model.thrift
- thrift-interface-descriptions/service-cpis/profile-service/profile-tenant/profile-tenant-cpi.thrift
Modified TenantProfileServiceHandler.java to check for a duplicate add gateway request.
Checked if the gateway ID, name, URL was already present in the database with the status as approved.
> [AIRAVATA-2385] Checking for duplicate gateway request

- airavata-services/profile-service/profile-service-server/src/main/java/org/apache/airavata/service/profile/handlers/GroupManagerServiceHandler.java
The implementation _getAllMemberGroupsForUser()_ was available in the sharing registry module.
> Implemented getAllGroupsUserBelongs API method

- modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/appcatalog/ComputeResourceEntity.java
- modules/registry-refactoring/src/test/java/org/apache/airavata/registry/core/repositories/appcatalog/ComputeResourceRepositoryTest.java
Changes:
- `ComputeResourceEntity.gatewayUsageReporting` to boolean instead of boolean
> Registry Refactoring : ComputeResourceEntity fix

- modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/appcatalog/UserComputeResourcePreferenceEntity.java
- modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/appcatalog/UserComputeResourcePreferencePK.java
- modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/appcatalog/UserResourceProfileEntity.java
- modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/appcatalog/UserResourceProfilePK.java
- modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/appcatalog/UserStoragePreferenceEntity.java
- modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/appcatalog/UserStoragePreferencePK.java
- modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/repositories/appcatalog/UserComputeResourcePreferenceRepository.java
- modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/repositories/appcatalog/UserResourceProfileRepository.java
- modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/repositories/appcatalog/UserStoragePreferenceRepository.java
- modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/utils/DBConstants.java
- modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/utils/QueryConstants.java
- modules/registry-refactoring/src/main/resources/META-INF/persistence.xml
- modules/registry-refactoring/src/test/java/org/apache/airavata/registry/core/repositories/appcatalog/UserResourceProfileRepositoryTest.java
- modules/registry/registry-cpi/src/main/java/org/apache/airavata/registry/cpi/UsrResourceProfile.java
- modules/registry/registry-server/registry-api-service/src/main/java/org/apache/airavata/registry/api/service/handler/RegistryServerHandler.java
Implementation of UserResourceProfileRepository.java instead of the existing implementation class dependency.
Changes made - 
- Added the necessary entity classes.
- Override all the methods for the 2 repository classes.
- Tests for the repository classes.
- Made necessary changes to the RegistryServerHandler.java class.
> [AIRAVATA-2712] Refactoring App Catalog Implementation - UserResourceProfile

- dev-tools/ansible/helix.yml
- dev-tools/ansible/inventories/standalone/group_vars/helix/vars.yml
- dev-tools/ansible/inventories/standalone/hosts
- dev-tools/ansible/roles/helix_setup/defaults/main.yml
- dev-tools/ansible/roles/helix_setup/tasks/main.yml
- dev-tools/ansible/roles/helix_setup/templates/controller/airavata-server.properties.j2
- dev-tools/ansible/roles/helix_setup/templates/controller/logback.xml.j2
- dev-tools/ansible/roles/helix_setup/templates/participant/airavata-server.properties.j2
- dev-tools/ansible/roles/helix_setup/templates/participant/logback.xml.j2
- dev-tools/ansible/roles/helix_setup/templates/post-wm/airavata-server.properties.j2
- dev-tools/ansible/roles/helix_setup/templates/post-wm/logback.xml.j2
- dev-tools/ansible/roles/helix_setup/templates/pre-wm/airavata-server.properties.j2
- dev-tools/ansible/roles/helix_setup/templates/pre-wm/logback.xml.j2
- dev-tools/ansible/roles/job_monitor/defaults/main.yml
- dev-tools/ansible/roles/job_monitor/tasks/main.yml
- dev-tools/ansible/roles/job_monitor/templates/email-monitor/airavata-server.properties.j2
- dev-tools/ansible/roles/job_monitor/templates/email-monitor/email-config.yaml.j2
- dev-tools/ansible/roles/job_monitor/templates/email-monitor/logback.xml.j2
- dev-tools/ansible/roles/job_monitor/templates/realtime-monitor/airavata-server.properties.j2
- dev-tools/ansible/roles/job_monitor/templates/realtime-monitor/logback.xml.j2
- dev-tools/ansible/roles/kafka/defaults/main.yml
- dev-tools/ansible/roles/kafka/handlers/main.yml
- dev-tools/ansible/roles/kafka/tasks/main.yml
- dev-tools/ansible/roles/kafka/templates/kafka.service.j2
- dev-tools/ansible/roles/kafka/templates/server.properties.j2
Mainly two roles,
- kafka role
- helix_setup role
helix_setup role with the following functionalities,
- create Helix deployment directory
- download & unarchive Helix
- create a cluster
- copy distributions to helix deployment directory. Distributions of
Helix Controller, Helix Participant, Pre Work flow Manager, Post Work flow Manager, Email Monitor, & Realtime Monitor
- copy airavata server property files, logback configuration files, & configuration files
- stop the daemons
- start all the 6 daemons
> Ansible Changes for helix-distribution

- airavata-api/airavata-client-sdks/airavata-php-sdk/src/main/resources/lib/Airavata/Model/Experiment/Types.php
- airavata-api/airavata-client-sdks/airavata-python-sdk/src/main/resources/lib/airavata/model/experiment/ttypes.py
- airavata-api/airavata-data-models/src/main/java/org/apache/airavata/model/experiment/ExperimentSearchFields.java
- modules/ide-integration/src/main/resources/pga/airavata-php-gateway/app/controllers/ExperimentController.php
- modules/ide-integration/src/main/resources/pga/airavata-php-gateway/app/libraries/Airavata/Model/Experiment/Types.php
- modules/ide-integration/src/main/resources/pga/airavata-php-gateway/app/libraries/ExperimentUtilities.php
- modules/ide-integration/src/main/resources/pga/airavata-php-gateway/app/routes.php
- modules/ide-integration/src/main/resources/pga/airavata-php-gateway/app/views/admin/manage-experiments.blade.php
- modules/registry/registry-core/src/main/java/org/apache/airavata/registry/core/repositories/expcatalog/ExperimentSummaryRepository.java
- modules/registry/registry-core/src/main/java/org/apache/airavata/registry/core/utils/DBConstants.java
- modules/registry/registry-server/registry-api-service/src/main/java/org/apache/airavata/registry/api/service/handler/RegistryServerHandler.java
- pom.xml
- thrift-interface-descriptions/data-models/experiment-catalog-models/experiment_model.thrift
I have added functionality in the PGA to search experiments using the jobId. It uses an existing API function searchExperiment() to first search the experiments using a new field 'JobId'. This new field is added to the experiment_model.thrift file.
After searching the corresponding experimentid using jobid, the normal flow of information follows i.e, the experiment Id is used to search a detailed view of the experiment and then presented to the user. 
The below screenshot displays the functionality.
> Improvement for Jira 1870 - provide ability to search experiments by jobId in the experiment statistics tab under admin dashboard

- modules/registry/registry-core/src/main/java/org/apache/airavata/registry/core/utils/AppCatalogDBInitConfig.java
- modules/registry/registry-core/src/test/java/org/apache/airavata/registry/core/repositories/appcatalog/UserResourceProfileRepositoryTest.java
- modules/sharing-registry/sharing-registry-server/src/test/java/org/apache/airavata/sharing/registry/SharingRegistryServerHandlerTest.java
UserResourceProfileRepositoryTest
The test case was failing due to failing assert statement. userResourceProfileRepository has 2 user resource profiles. A default user resource profile is added during appCatalog DB Initialization, 2nd user profile is added during testing.
SharingRegistryServerHandlerTest
Test case was failing due to failure to initialize sharing registry db. The sharingRegistryDBInitConfig being created was not being used during the creation of SharingRegistryServerHandler.
> fixed failing test cases

- airavata-api/airavata-client-sdks/airavata-python-sdk/airavata_python_sdk.egg-info/SOURCES.txt
- airavata-api/airavata-client-sdks/airavata-python-sdk/clients/sftp_file_handling_client.py
- airavata-api/airavata-client-sdks/airavata-python-sdk/clients/utils/data_model_creation_util.py
- difficult to make pysftp work with windows path (https://stackoverflow.com/questions/50118919/python-pysftp-get-r-from-linux-works-fine-on-linux-but-not-on-windows), so switch to paramiko. 
- also use hard-coded storage-id, because non-privildge gateway users fail in airavata_util.get_storage_resource_id
> swtich to paramiko sftp for windows path

- modules/airavata-helix/helix-spectator/src/main/java/org/apache/airavata/helix/impl/task/submission/config/GroovyMapData.java
The current implementation only resolves the parameters in the original groovy template. But if we pass parameters inside the map which contains parameters themselves, those are not resolved. This fix does another pass of parameter parsing on the already generated template output
Related issue: https://issues.apache.org/jira/browse/AIRAVATA-3391
> Fixing AIRAVATA-3391 : Resolving parameters in the groovy map data

- modules/airavata-helix/helix-spectator/src/main/java/org/apache/airavata/helix/impl/task/staging/DataStagingTask.java
- modules/airavata-helix/helix-spectator/src/main/java/org/apache/airavata/helix/impl/task/staging/OutputDataStagingTask.java
In some cases output files might have special characters in the name which causes trouble for SCP protocol to handle. This fix will rename those files
> Handling special characters in output staging

- modules/ide-integration/README.md
- modules/ide-integration/src/main/resources/email-config.yaml
* Fixed the following issue changing - "HTCondor" to "HTCONDOR"
`Exception in thread "main" java.lang.IllegalArgumentException: No enum constant org.apache.airavata.model.appcatalog.computeresource.ResourceJobManagerType.HTCondor at java.base/java.lang.Enum.valueOf(Enum.java:240) at org.apache.airavata.model.appcatalog.computeresource.ResourceJobManagerType.valueOf(ResourceJobManagerType.java:50) at org.apache.airavata.monitor.email.EmailBasedMonitor.lambda$loadContext$0(EmailBasedMonitor.java:106) at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) at org.apache.airavata.monitor.email.EmailBasedMonitor.loadContext(EmailBasedMonitor.java:103) at org.apache.airavata.monitor.email.EmailBasedMonitor.init(EmailBasedMonitor.java:73) at …
> Fixed enum constant issue and updated the readme to align with new gmail security changes

- airavata-services/profile-service/iam-admin-services-core/pom.xml
The existing httpclient version is incompatible with the rest-easy-client
```text
Exception in thread "TThreadPoolServer WorkerProcess-64" java.lang.NoSuchMethodError: 'org.apache.http.ssl.SSLContextBuilder org.apache.http.ssl.SSLContextBuilder.setProtocol(java.lang.String)'
at org.jboss.resteasy.client.jaxrs.engines.ClientHttpEngineBuilder43.build(ClientHttpEngineBuilder43.java:113)
at org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl.build(ResteasyClientBuilderImpl.java:392)
at org.apache.airavata.service.profile.iam.admin.services.core.impl.TenantManagementKeycloakImpl.getResteasyClient(TenantManagementKeycloakImpl.java:98)
at org.apache.airavata.service.profile.iam.admin.services.core.impl.TenantManagementKeycloakImpl.getClient(TenantManagementKeycloakImpl.java:79)
at …
```
> Removed redundant httpclient dependency from IAM admin services core

- airavata-api/airavata-client-sdks/airavata-python-sdk/pyproject.toml
- airavata-api/airavata-client-sdks/airavata-python-sdk/requirements.txt
- airavata-api/airavata-client-sdks/airavata-python-sdk/setup.py
Currently when installing airavata-python-sdk through pip, its dependencies are not installed. I updated setup.py to install the dependencies specified in requirements.txt in the install step.
> install dependencies of airavata-python-sdk

- modules/distribution/src/main/assembly/controller-bin-assembly.xml
- modules/distribution/src/main/assembly/email-monitor-bin-assembly.xml
- modules/distribution/src/main/assembly/parser-wm-bin-assembly.xml
- modules/distribution/src/main/assembly/participant-bin-assembly.xml
- modules/distribution/src/main/assembly/post-wm-bin-assembly.xml
- modules/distribution/src/main/assembly/pre-wm-bin-assembly.xml
- modules/distribution/src/main/assembly/realtime-monitor-bin-assembly.xml
- pom.xml
Replaced `log4j-slf4j-impl` with `log4j-slf4j2-impl` to ensure compatibility with SLF4J 2.x
```
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J(W): Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J(W): Ignoring binding found at [jar:file:/home/airavata/master-deployment/api-orchestrator/apache-airavata-api-server-0.21-SNAPSHOT/lib/log4j-slf4j-impl-2.23.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J(W): See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```
> Upgrade to log4j-slf4j2-impl for SLF4J 2.x compatibility

- modules/ide-integration/src/main/containers/docker-compose.yml
- modules/ide-integration/src/main/containers/keycloak/Default-export.json
Fixes: Database setup errors and Keycloak configuration
This new PR addresses two key issues that I encountered in the development environment setup:
1. **Outdated Keycloak Image and Configuration:**
* The keycloak version is updated to version 24.0.0 (the old version was out of date)
* Adjusts the Keycloak command to ensure proper realm import and hostname handling for development purposes.
2. **MariaDB Volume Binding for macOS Compatibility:**
* Modifies the MariaDB volume binding to utilize a Docker volume instead of a direct host path. This resolves potential ".frm" errors caused by file system inconsistencies between macOS and the Docker environment.
I can confirm that the .frm issues with maria db was a recurring issue that occurred on multiple arm based mac-os machines. I was able …
> Updating docker-compose.yml file to fix database setup errors and setup keycloak properly on version 24.0.0

- modules/research-framework/portal/src/App.tsx
- modules/research-framework/portal/src/components/home/StartSessionFromProjectButton.tsx
- modules/research-framework/portal/src/components/resources/ResourceDetails.tsx
- modules/research-framework/portal/src/components/resources/index.tsx
- modules/research-framework/portal/src/lib/constants.ts
**Updates:**
- Updated coloring for resource types (filters now show as colored): dataset = green, notebook = blue, model = purple, repo = red
- When user is not logged in, and they click "start project session", the redirect back will automatically open the start modal
**Demo**:
https://github.com/user-attachments/assets/edc5fc81-5782-48c7-9141-fa0a99d40b23
> support auto open start project modal on login

- README.md
This PR introduces a new section to the README.md titled “Airavata Component Ecosystem”, which outlines the key modules and repositories that make up the broader Apache Airavata ecosystem.
The section categorizes components into Core services, User interfaces, Data and metadata services, Documentation and branding, and Experimental and research projects.
This addition provides readers and contributors with a high-level view of the full project landscape, making it easier to understand the modular structure and navigate related repositories.
> Add details about the airavata ecosystem into README.md

- modules/research-framework/portal/src/components/resources/ResourceDetails.tsx
Currently, if a user tries to access a resource with invalid id, they will be shown an infinite loading state. This PR fixes that.
Addresses https://github.com/cyber-shuttle/cybershuttle/issues/34
> Show error toast if user navigates to a resource with invalid ID

- dev-tools/ansible/inventories/scigap/develop/group_vars/all/vars.yml
- dev-tools/ansible/inventories/standalone/group_vars/all/vars.yml
- dev-tools/ansible/inventories/template/group_vars/all/vars.yml
- dev-tools/ansible/roles/keycloak/defaults/main.yml
- pom.xml
Fixes [CVE-2023-22102](https://nvd.nist.gov/vuln/detail/CVE-2023-22102)
> update from mysql-connector-java:5 (vulnerable) to mysql-connector-j:9
