apache/airavata

airavata-api/airavata-api-server/src/test/java/org/apache/airavata/api/server/handler/AiravataServerHandlerTest.java

This is an intermediate PR since there were some compilation errors in tests due to API changes.

Fixing errors in AiravataServerHandlerTest, when building the master with tests enabled.

---

modules/cloud/cloud-provisioning/README
modules/cloud/cloud-provisioning/pom.xml
modules/cloud/cloud-provisioning/src/main/java/org/apache/airavata/cloud/intf/CloudInterface.java
modules/cloud/cloud-provisioning/src/main/java/org/apache/airavata/cloud/intf/impl/OpenstackIntfImpl.java
modules/cloud/cloud-provisioning/src/main/java/org/apache/airavata/cloud/util/IPType.java
modules/cloud/cloud-provisioning/src/main/resources/jetstream_openrc.properties
modules/cloud/cloud-provisioning/src/test/java/org/apache/airavata/cloud/test/CloudIntfTest.java
modules/cloud/cloud-provisioning/src/test/resources/test_data.properties
modules/cloud/pom.xml

Following are the main changes added with this request:-
1) Added method to Cloud Interface to associate floating ip. The floating ip will also get deallocated on deletion of server instance.
2) Changed the methods to use network name instead of network id, read from the properties, for better understanding.
3) Added log statements in the OpenStack implementation.

Floating IP assoication changes.

---

modules/group-manager/src/main/java/org/apache/airavata/grouper/group/Group.java
modules/group-manager/src/main/java/org/apache/airavata/grouper/group/GroupService.java
modules/group-manager/src/main/java/org/apache/airavata/grouper/group/GroupServiceImpl.java
modules/group-manager/src/main/java/org/apache/airavata/grouper/resource/ResourceServiceImpl.java
modules/group-manager/src/main/java/org/apache/airavata/grouper/role/RoleServiceImpl.java

Add method to get user memberships. Allow the owner of the group to make updates

Add method to get user memberships. Allow the owner of the group to make updates

---

modules/registry-refactoring/src/test/java/org/apache/airavata/registry/core/repositories/RepositoryTest.java

- Written a Junit Test class named RepositoryTest.java for registry-refactoring module.
The RepositoryTest tests CRUDE operations for GatewayRepository, NotificationRepository, UserProfileRepository and ProjectRepository.

Repostory Junit test

---

modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/workflowcatalog/ComponentStatusEntity.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/workflowcatalog/EdgeEntity.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/workflowcatalog/EdgePK.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/workflowcatalog/NodeEntity.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/workflowcatalog/NodePK.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/workflowcatalog/PortEntity.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/workflowcatalog/PortPK.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/workflowcatalog/WorkflowEntity.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/workflowcatalog/WorkflowInputEntity.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/workflowcatalog/WorkflowInputPK.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/workflowcatalog/WorkflowOutputEntity.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/workflowcatalog/WorkflowOutputPK.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/workflowcatalog/WorkflowStatusEntity.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/entities/workflowcatalog/WorkflowStatusPK.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/repositories/workflowcatalog/ComponentStatusRepository.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/repositories/workflowcatalog/EdgeRepository.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/repositories/workflowcatalog/NodeRepository.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/repositories/workflowcatalog/PortRepository.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/repositories/workflowcatalog/WorkflowRepository.java
modules/registry-refactoring/src/main/java/org/apache/airavata/registry/core/repositories/workflowcatalog/WorkflowStatusRepository.java
modules/registry-refactoring/src/test/java/org/apache/airavata/registry/core/repositories/RepositoryTest.java

The pull request contains 2 commits.
1. New Entity class has been created for the Workflow Catalog related tables
2. Corresponding Repositories has been created

Registry refactoring Workflow Catalog Entities and Related Repositories

---

modules/registry/registry-core/src/main/java/org/apache/airavata/registry/core/app/catalog/impl/UsrResourceProfileImpl.java
modules/registry/registry-core/src/main/java/org/apache/airavata/registry/core/app/catalog/resources/UserStoragePreferenceResource.java
modules/registry/registry-core/src/test/java/org/apache/airavata/app/catalog/UserResourceProfileTest.java

###Bug is resolved:
https://issues.apache.org/jira/browse/AIRAVATA-2152?focusedCommentId=15595600&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15595600
https://issues.apache.org/jira/browse/AIRAVATA-2152?focusedCommentId=15595650&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15595650

Resolving User storage preference bugs

---

airavata-api/airavata-api-server/src/main/java/org/apache/airavata/api/server/handler/AiravataServerHandler.java
airavata-api/airavata-data-models/src/main/java/org/apache/airavata/model/appcatalog/credentialsummary/CredentialSummary.java
modules/credential-store/credential-store-service/src/main/java/org/apache/airavata/credential/store/store/impl/db/CredentialsDAO.java
modules/credential-store/credential-store-service/src/test/java/org/apache/airavata/credential/store/cpi/SSHSummaryTest/SSHSummaryTest.java
modules/credential-store/credential-store-service/src/test/java/org/apache/airavata/credential/store/store/impl/db/CredentialsDAOTest.java
thrift-interface-descriptions/data-models/resource-catalog-models/credential_summary.thrift

The token field was missing, which apparently is an dependency when configuring the User Compute Preference.

adding token to credential summary model

---

modules/registry/registry-core/src/main/java/org/apache/airavata/registry/core/app/catalog/resources/UserResourceProfileResource.java

* Resolved save method bug, it now accepts (userId, GatewayID).
* https://issues.apache.org/jira/browse/AIRAVATA-2231

AIRAVATA-2231 : Bug in UserResourceProfile.save() method 

---

airavata-api/airavata-api-server/src/main/java/org/apache/airavata/api/server/handler/AiravataServerHandler.java
airavata-api/airavata-client-sdks/airavata-php-sdk/src/main/resources/lib/Airavata/API/Airavata.php
modules/registry/registry-core/src/main/java/org/apache/airavata/registry/core/experiment/catalog/impl/ExperimentRegistry.java
modules/registry/registry-core/src/main/java/org/apache/airavata/registry/core/experiment/catalog/resources/WorkerResource.java
modules/registry/registry-cpi/src/main/java/org/apache/airavata/registry/cpi/utils/Constants.java
modules/registry/registry-server/registry-api-service/src/main/java/org/apache/airavata/registry/api/service/handler/RegistryServerHandler.java
thrift-interface-descriptions/airavata-apis/airavata_api.thrift
thrift-interface-descriptions/component-cpis/registry-api.thrift

Adds the three more experiment statistics filtering options to the API
* username
* application id
* hostname id

AIRAVATA-1792 Implement ability for admin to search for experiments using the created user as well

---

airavata-api/airavata-client-sdks/airavata-php-sdk/src/main/resources/lib/Airavata/API/Airavata.php
airavata-api/airavata-client-sdks/airavata-php-sdk/src/main/resources/lib/Airavata/Model/Credential/Store/Types.php
modules/credential-store/credential-store-service/src/main/java/org/apache/airavata/credential/store/server/CredentialStoreServerHandler.java

Setting 'type' since it is required on CredentialSummary.

AIRAVATA-2163 Setting type on CredentialSummary

---

modules/registry/registry-core/src/main/java/org/apache/airavata/registry/core/app/catalog/util/AppCatalogThriftConversion.java

Fix for setting gateway usage reporting id.
Set it to gateway id if gateway usage reporting id is not present
Jira: AIRAVATA-2317

Fix for setting usage reporting id.

---

modules/gfac/gfac-impl/src/main/java/org/apache/airavata/gfac/impl/SSHUtils.java

Adding additional logging to identify root cause of file transfer issue.
These changes can be reverted after fixing the same.

adding logs to identify file transfer issue

---

modules/compute-account-provisioning/pom.xml
modules/compute-account-provisioning/src/main/java/org/apache/airavata/accountprovisioning/provisioner/IULdapSSHAccountProvisioner.java
modules/compute-account-provisioning/src/test/java/org/apache/airavata/accountprovisioning/SSHAccountProvisionerFactoryTest.java
modules/compute-account-provisioning/src/test/java/org/apache/airavata/accountprovisioning/provisioner/TestSSHAccountProvisionerProvider.java

Please look at the pull request

AIRAVATA-2500 Partial Implementation

---

airavata-services/profile-service/profile-service-server/src/main/java/org/apache/airavata/service/profile/handlers/GroupManagerServiceHandler.java
airavata-services/profile-service/profile-service-stubs/src/main/java/org/apache/airavata/service/profile/groupmanager/cpi/GroupManagerService.java
modules/sharing-registry/sharing-registry-server/src/main/java/org/apache/airavata/sharing/registry/server/SharingRegistryServerHandler.java
modules/sharing-registry/sharing-registry-server/src/test/java/org/apache/airavata/sharing/registry/SharingRegistryServerHandlerTest.java
modules/sharing-registry/sharing-registry-server/src/test/java/org/apache/airavata/sharing/registry/SharingRegistryServiceTest.java
thrift-interface-descriptions/service-cpis/profile-service/group-manager/group-manager-cpi.thrift

**Changes**:
- Added two API methods to the GroupMangerService `addUsersToGroup()` and `removeUsersFromGroup`
- Added necessary auth checks for owner and admin

[AIRAVATA-2679]  [AIRAVATA-2680] GroupManagerService: Auth checks and add/remove users from group

---

modules/messaging/core/src/main/java/org/apache/airavata/messaging/core/impl/RabbitMQPublisher.java

Currently, using a RabbitMQ publisher multiple threads can publish to the broker through a single channel. However RabbitMQ mentions not to reuse same channel among multiple threads as it is not thread safe. So I used a thread local to store the channel object and each thread will use a separate channel object.

Using one RabbitMQ Channel for one thread

---

modules/airavata-helix/helix-spectator/src/main/java/org/apache/airavata/helix/impl/participant/GlobalParticipant.java
modules/airavata-helix/task-core/src/main/java/org/apache/airavata/helix/core/participant/HelixParticipant.java
modules/airavata-helix/workflow-impl/src/main/java/org/apache/airavata/helix/workflow/QueueOperator.java

Changes to the existing Helix based Task Framework to support User Defined Workflow implementation

Updating Task Framework to support User Defined Workflow implementation

---

modules/ide-integration/README.md

I added direct link to npm(https://www.npmjs.com/get-npm) so that if folks need to update there is a quick command to run along with download option.

updated README.md

---

airavata-services/profile-service/profile-service-client-sdks/java-client-samples/src/main/java/org/apache/airavata/service/profile/client/samples/UserProfileSample.java
airavata-services/profile-service/profile-service-commons/src/main/java/org/apache/airavata/service/profile/commons/tenant/entities/GatewayEntity.java
modules/credential-store/credential-store-service/src/main/java/org/apache/airavata/credential/store/store/impl/db/CredentialsDAO.java
modules/gfac/gfac-bes/src/main/java/org/apache/airavata/gfac/bes/security/X509SecurityContext.java
modules/gfac/gfac-impl/src/main/java/org/apache/airavata/gfac/impl/GFacEngineImpl.java
modules/gfac/gfac-impl/src/main/java/org/apache/airavata/gfac/impl/task/utils/bes/X509SecurityContext.java
modules/gfac/gfac-impl/src/main/java/org/apache/airavata/gfac/monitor/email/EmailBasedMonitor.java
modules/orchestrator/orchestrator-core/src/main/java/org/apache/airavata/orchestrator/cpi/impl/SimpleOrchestratorImpl.java
modules/user-profile-migration/src/main/java/org/apache/airavata/MigrationManager.java

same pr as #218 to use System.currentTimeMillis()

use System.currentTimeMillis()

---

modules/ide-integration/src/main/resources/airavata-server.properties
pom.xml

_modified:   modules/ide-integration/src/main/resources/airavata-server.properties_
Updated changed the server.host from localhost to 0.0.0.0 as the localhost as localhost was creating problems in Linux where
the docker container was not able to talk to the API services due to a different host address.
_modified:   pom.xml_
1. Added maven repository as maven was not able to download some libraries from already available repos.
2. Added a plugin for openJPA to avoid the following error in Intellij:
"<openjpa-2.4.3 nonfatal user error> org.apache.openjpa.persistence.ArgumentException: This configuration disallows runtime optimization, but the following listed types were not enhanced at build time or at class load time with a javaagent: "

Fixing two issues encountered during the setup of development environment in Ubuntu OS

---

pom.xml

I have fixed the typo that Bibrak had pointed.

Fixing a typo in artifactId

---

airavata-services/profile-service/profile-service-server/src/main/java/org/apache/airavata/service/profile/handlers/GroupManagerServiceHandler.java

Fixed bug https://issues.apache.org/jira/browse/AIRAVATA-3111

refactored the create group method to add admins in the group

---

airavata-services/profile-service/iam-admin-services-core/pom.xml
modules/distribution/pom.xml
pom.xml

https://issues.apache.org/jira/browse/AIRAVATA-3590

AIRAVATA-3590: jackson 2.9.10.8

---

pom.xml

https://issues.apache.org/jira/browse/AIRAVATA-3590

AIRAVATA-3590 upgrade log4j and commons-io

---

modules/airavata-helix/helix-spectator/src/main/java/org/apache/airavata/helix/impl/task/staging/DataStagingTask.java
modules/airavata-helix/helix-spectator/src/main/java/org/apache/airavata/helix/impl/task/staging/OutputDataStagingTask.java

This reverts commit fbdbff47ba91067d3dda711f78972252246b1c36.

Revert "Handling special characters in output staging"

---

modules/agent-framework/connection-service/pom.xml
modules/agent-framework/connection-service/src/main/java/org/apache/airavata/agent/connection/service/controllers/ExperimentController.java
modules/agent-framework/connection-service/src/main/java/org/apache/airavata/agent/connection/service/handlers/ExperimentHandler.java
modules/agent-framework/connection-service/src/main/java/org/apache/airavata/agent/connection/service/services/AiravataService.java

* Added endpoints to get, create, and launch experiements
@DImuthuUpe please give it a look

Experiment APIs for agent-framework

---

pom.xml

removed duplicated module definition to fix the build issue

Removed the duplicated module definition: 'org.apache.airavata:connection-service'

---

airavata-api/airavata-api-server/pom.xml
airavata-api/airavata-client-sdks/java-client-samples/pom.xml
airavata-services/profile-service/iam-admin-services-core/pom.xml
airavata-services/services-security/pom.xml
modules/airavata-helix/agent-impl/sshj-agent/pom.xml
modules/airavata-helix/agent-impl/sshj-agent/src/main/java/org/apache/airavata/helix/adaptor/SSHJAgentAdaptor.java
modules/airavata-helix/agent-impl/sshj-agent/src/main/java/org/apache/airavata/helix/adaptor/wrapper/SCPFileTransferWrapper.java
modules/distribution/pom.xml
modules/ide-integration/src/main/containers/pga/airavata-php-gateway/app/tests/selenium/pom.xml
pom.xml

Related JIRA - https://issues.apache.org/jira/browse/AIRAVATA-3918

Upgrade sshj library version

---

.gitignore
modules/research-framework/research-service/pom.xml
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/ResponseTypes/ResourceResponse.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/controller/ProjectController.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/controller/UserController.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/enums/PrivacyEnum.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/enums/ResourceTypeEnum.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/enums/StatusEnum.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/exception/ErrorResponse.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/exception/GlobalExceptionHandler.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/handlers/ProjectHandler.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/handlers/UserHandler.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/entity/DatasetResource.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/entity/ModelResource.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/entity/NotebookResource.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/entity/RepositoryResource.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/entity/Resource.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/entity/Tag.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/entity/User.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/repo/ResourceRepository.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/repo/TagRepository.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/repo/UserRepository.java
modules/research-framework/research-service/src/main/proto/research-service.proto
modules/research-framework/research-service/src/main/resources/application.yml

Research Framework

---

modules/research-framework/portal/src/App.tsx
modules/research-framework/portal/src/components/NavBar.tsx
modules/research-framework/portal/src/components/datasets/index.tsx
modules/research-framework/portal/src/components/home/ProjectCard.tsx
modules/research-framework/portal/src/components/home/ProjectsSection.tsx
modules/research-framework/portal/src/components/home/ResourceCard.tsx
modules/research-framework/portal/src/components/home/SessionCard.tsx
modules/research-framework/portal/src/components/home/SessionsSection.tsx
modules/research-framework/portal/src/components/home/index.tsx
modules/research-framework/portal/src/components/models/ModelSpecificBox.tsx
modules/research-framework/portal/src/components/models/index.tsx
modules/research-framework/portal/src/components/notebooks/index.tsx
modules/research-framework/portal/src/components/repositories/index.tsx
modules/research-framework/portal/src/components/resources/ResourceDetails.tsx
modules/research-framework/portal/src/interfaces/ProjectType.tsx
modules/research-framework/portal/src/interfaces/SessionStatusEnum.ts
modules/research-framework/portal/src/interfaces/SessionType.tsx
modules/research-framework/portal/src/lib/util.ts
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/config/DevDataInitializer.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/controller/ResearchHubController.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/enums/SessionStatusEnum.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/handlers/ResearchHubHandler.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/handlers/SessionHandler.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/entity/Project.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/entity/Session.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/repo/SessionRepository.java
modules/research-framework/research-service/src/main/resources/application.yml

https://github.com/user-attachments/assets/f79f65b8-6a4b-4513-a936-b132410e37a8

Prepare for demo

---

modules/research-framework/portal/src/components/notebooks/ProjectDetails.tsx

Added a file tree that looks like this:

File tree added to ProjectDetails.tsx

---

airavata-api/airavata-client-sdks/airavata-python-sdk/airavata_jupyter_magic/__init__.py
modules/agent-framework/agent-service/src/main/resources/application.yml
modules/agent-framework/airavata-agent/agent.go

Ability to render HTML and JS display types on cell output

Support for HTML and JS support for magic output

---

modules/research-framework/portal/src/App.tsx
modules/research-framework/portal/src/components/auth/Login.tsx
modules/research-framework/portal/src/components/events/index.tsx
modules/research-framework/portal/src/components/home/SessionCard.tsx
modules/research-framework/portal/src/components/home/SessionsSection.tsx
modules/research-framework/portal/src/components/repositories/RepositorySpecificDetails.tsx
modules/research-framework/portal/src/components/resources/index.tsx
modules/research-framework/portal/src/layouts/NavBar.tsx

- only show created / terminated status for sessions
- change github button location
- re-order resource and change pre-check
- add events page

UI/UX Changes to RF Portal + Events Page

---

modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/handlers/ResearchHubHandler.java

https://github.com/user-attachments/assets/ba149d36-df67-4601-8453-52b4684d6daf

Support multiple datasets

---

modules/research-framework/portal/src/components/auth/UserMenu.tsx
modules/research-framework/portal/src/components/events/Apr11Workshop.tsx
modules/research-framework/portal/src/components/events/May7Workshop.tsx
modules/research-framework/portal/src/components/events/index.tsx
modules/research-framework/portal/src/components/resources/index.tsx
modules/research-framework/portal/src/components/typography/KeyPair.tsx
modules/research-framework/portal/src/layouts/NavBar.tsx

https://github.com/user-attachments/assets/73ab4163-22cc-4e77-9c71-1cb18c794a3d

may 7 workshop agenda + resource filtering

---

pom.xml

https://issues.apache.org/jira/browse/AIRAVATA-3590

AIRAVATA-3590 upgrade snakeyaml due to XXE issue

---

tools/load-client/src/main/java/org/apache/airavata/tools/load/SecurityManager.java

Leave a comment to warn that it is not secure

Leave a comment to warn that it is not secure

---

modules/research-framework/portal/src/components/home/ResourceCard.tsx
modules/research-framework/portal/src/components/resources/index.tsx
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/controller/ResourceController.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/handlers/ResourceHandler.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/repo/ResourceRepository.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/repo/TagRepository.java

Addresses https://github.com/cyber-shuttle/cybershuttle/issues/12
https://github.com/user-attachments/assets/3f809273-3f71-4686-b667-9cf1ca7c6c77

Support better text search

---

modules/research-framework/portal/src/components/add/AddGitUrl.tsx
modules/research-framework/portal/src/components/add/AddProjectMaster.tsx
modules/research-framework/portal/src/components/add/DatasetSearch.tsx
modules/research-framework/portal/src/components/add/RepoSearch.tsx
modules/research-framework/portal/src/components/home/ProjectCard.tsx
modules/research-framework/portal/src/components/home/ResourceCard.tsx
modules/research-framework/portal/src/components/notebooks/index.tsx
modules/research-framework/portal/src/components/projects/DeleteProjectButton.tsx
modules/research-framework/portal/src/components/resources/DeleteResourceButton.tsx
modules/research-framework/portal/src/components/resources/ResourceDetails.tsx
modules/research-framework/portal/src/components/resources/ResourceTypeBadge.tsx
modules/research-framework/portal/src/components/resources/index.tsx
modules/research-framework/portal/src/interfaces/ProjectType.tsx
modules/research-framework/portal/src/lib/util.ts
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/config/AuthzTokenFilter.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/controller/ProjectController.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/controller/ResourceController.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/enums/StateEnum.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/handlers/ProjectHandler.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/handlers/ResourceHandler.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/entity/Project.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/entity/Resource.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/repo/ProjectRepository.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/repo/ResourceRepository.java
modules/research-framework/research-service/src/main/resources/application.yml

Addresses: https://github.com/cyber-shuttle/cybershuttle/issues/13
When a resource / project is "deleted", we simply set the "state" property on that hibernate entity to be DELETED. If we were to delete the hibernate entity completely, that would mess up foreign key relationships with already existing projects that depend on a deleted resource. Or, completely deleting a project entity may create issues with sessions, which may be created by other users. Thus, we simply mark the project/resource as deleted, and never return it in any future search results
https://github.com/user-attachments/assets/624e4b33-0c4f-4e3d-bf71-f69d63e8557f
https://github.com/user-attachments/assets/da3b646c-58bc-47ef-8967-8142b19c32fd

Support resource deletion

---

modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/config/AuthzTokenFilter.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/controller/ResourceController.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/handlers/ResourceHandler.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/UserContext.java
modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/model/repo/ResourceRepository.java

**Demo Video**:
https://github.com/user-attachments/assets/af7be378-6bc1-407c-9c02-4aa7b2882af2
Backend support for https://github.com/cyber-shuttle/cybershuttle/issues/35

Public private resources

---

modules/research-framework/research-service/src/main/java/org/apache/airavata/research/service/controller/SessionController.java

Backend support for https://github.com/cyber-shuttle/cybershuttle/issues/58

backend support for all sessions deletion
